llm_name: qwen3_4b
model_path: /data/lyz/models/Qwen3-4B
default_model: Qwen3-4B
max_concurrent_requests: 32

vllm:
  remote: false
  host: 0.0.0.0
  port: 8001
  gpu_ids: "1"
  tensor_parallel_size: 1
  max_model_len: 32768
  gpu_memory_utilization: 0.9
  max_logprobs: 100
  extra_args:
    - "--dtype=half"
  endpoints: []
  api_keys: []
